##################################################################################
# Cloudify BIG-IP built in types and plugins definitions.
##################################################################################
plugins:
    bigip:
        executor: central_deployment_agent
        package_name: cloudify-bigip-plugin
        package_version: '1.0.0'
        source: https://github.com/nandomatarese/cloudify-bigip-nfv-plugin/archive/master.zip

relationships:
    cloudify.bigip.pool_to_endpoint:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                establish:
                    implementation: bigip.bigip_plugin.tasks.add_member
                    inputs:
                        address:
                            description: host address to add to the pool
                            type: string
                            default: { get_attribute: [ TARGET, floating_ip_address] }
                        port:
                            description: host address to add to the pool
                            type: integer
                unlink:
                    implementation: bigip.bigip_plugin.tasks.remove_member
                    inputs:
                        address:
                            description: host address to remove from the pool
                            type: string
                            default: { get_attribute: [ TARGET, floating_ip_address] }
                        port:
                            description: port to remove from the pool
                            type: integer

    cloudify.bigip.pool_to_application:
        derived_from: cloudify.relationships.depends_on

node_types:
    cloudify.bigip.nodes.Pool:
        derived_from: cloudify.nodes.LoadBalancer
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: bigip.bigip_plugin.tasks.create_pool
                delete:
                    implementation: bigip.bigip_plugin.tasks.delete_pool
        properties:
            host:
                description: Hostname / address of the BIG-IP server
                type: string
            username:
                description: Username to authenticate to BIG-IP with
                type: string
            password:
                description: Password to authenticate to BIG-IP with
                type: string
            pool_id:
                description: pool's identifier
                type: string
            lb_method:
                description: load-balancing method
                type: string
                default: LB_METHOD_ROUND_ROBIN
